[tool.black]
line-length = 88  # Максимальная длина строки
target-version = ["py311"]  # Версия Python для которой написан код
# Список файлов и папок которые Black должен игнорировать
exclude = """  
(
    /venv   # Игнорировать папку venv в корне проекта
  | /.venv   # Игнорировать скрытую папку .venv в корне проекта
  | /data
  | /images
)
"""

[tool.ruff]  # Секция настроек для линтера Ruff
line-length = 88
target-version = "py311"
extend-exclude = ["venv", ".venv", "data", "images"]

[tool.ruff.lint]  # Настройки линтинга для Ruff
select = ["E", "F", "I"]
# E - ошибки форматирования и синтаксиса
# F - неиспользуемые переменные, импорты, неопределенные имена
# I - правильность сортировки импортов
ignore = ["E501"]  # Игнорировать правило "line too long" (строка слишком длинная)